
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install Maven
      become: yes
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
        - maven

    - name: Ensure sonarqube group exists
      group:
        name: sonarqube
        state: present

    - name: Create a Sonarqube user
      user:
        name: sonarqube
        password: YhsqiF.YODrJI
        groups: docker, sudo, sonarqube
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/sonarqube

    - name: Execute docker pull in container
      command: docker pull sonarqube

    - name: Execute docker sonarqube run command in container
      command: docker run -d --name sonarqube -p 9000:9000 sonarqube

    - name: Execute Maven clean installwq
      command: mvn clean install sonar:sonar
