---
- hosts: all
  remote_user: root
  become: true

  tasks:
    - name: Create folders
      file:
        path: /opt/artifactory/var/etc
        state: directory

    - name: Create folders and files
      file:
        path: /opt/artifactory/var/etc/system.yaml
        state: touch

    - name: Change permissions
      command: "{{ item }}"
      with_items:
        - chown -R 1030:1030 /opt/artifactory/var

    - name: Start Artifactory
      command: docker run --name artifactory -v /opt/artifactory/var/:/var/opt/jfrog/artifactory -d -p 8081:8081 -p 8082:8082 docker.bintray.io/jfrog/artifactory-cpp-ce:latest
