---
- hosts: all
  remote_user: root
  become: true

  tasks:
    - name: Remove the previous calculator container
      command: "{{ item }}"
      with_items:
        - docker rm -f calculator

    - name: Copy Dockerfile to application server
      copy:
        src: /var/jenkins_home/workspace/Terraform_master/Dockerfile
        dest: /home/ubuntu/Dockerfile

    - name: Create Docker image
      command: "{{ item }}"
      with_items:
        - docker build -f /home/ubuntu/Dockerfile -t l00144427/calculator .

