---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Ensure sonarqube group exists
      group:
        name: sonarqube
        state: present

    - name: Create a Sonarqube user
      user:
        name: sonarqube
        password: YhsqiF.YODrJI
        groups: docker, sudo, sonarqube
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/sonarqube

    - name: Create sonarqube_data volume
      command: docker volume create --name sonarqube_data

    - name: Create sonarqube_extensions volume
      command: docker volume create --name sonarqube_extensions

    - name: Create sonarqube_logs volume
      command: docker volume create --name sonarqube_logs

    - name: Execute docker pull in container
      command: docker pull sonarqube

    - name: Check if Sonarqube container is already running. If the container doesn't exists it will create it and run. If the container is stopped it just start it
      command: docker start sonarqube || docker run --restart always -d --name sonarqube -p 9000:9000 sonarqube
