---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  vars:
    SONARQUBE_PASSWORD: "{{ sonarqube_password }}"

  tasks:
    - name: Ensure a sonarqube group exists
      group:
        name: sonarqube
        state: present

    - name: Ensure a sonarqube user exists
      user:
        name: sonarqube
        groups: docker, sudo, sonarqube
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/sonarqube

    - name: Create sonarqube_data volume
      command: docker volume create --name sonarqube_data

    - name: Create sonarqube_extensions volume
      command: docker volume create --name sonarqube_extensions

    - name: Create sonarqube_logs volume
      command: docker volume create --name sonarqube_logs

    #- name: Execute docker pull in container
    #  command: docker pull sonarqube

    #- name: Remove Sonarqube container
    #  command: docker rm -f sonarqube

    - name: Start the Sonarqube container
      command: docker start sonarqube || docker run --detach --name sonarqube -p 9000:9000 sonarqube
